### ISSUE TITLE
Make blog list look more like design

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#42]
Remove "Create blog post" and make formatting look more like the design:

![ ](http://i.imgur.com/exdmIs9.jpg)

**Comment by mbrakken** [comment]
See branch iss42-blog (not quite ready to merge)
- I'm ignoring the search in the side bar here (the first textfield labeled "Subscribe via Email") since it's redundant per #40 (unless we want to move the search bar at the top of the main content to the side). 
- I don't see an email subscription block yet, so that's not in there, either.
- Recent Posts on this page is redundant, since this is a page of recent posts. That block makes sense on individual posts, not the list. It's easily placed if necessary.
- With the Search API-based view, comment counts are not readily accessible. That will require custom coding if preferred.
- The mockup displays full posts, while the current implementation displays partials. I can switch this if preferred.
-  I'd like to put the "Search Blog" label as placeholder text and then hide the label in a way that is screen-reader friendly
- Also, need to replace search button with spyglass and then position it.
- The twitter block is there, but not shown because twitter module is not configured

**Comment by mbrakken** [comment]
Closing this with #54. See notes in PR.
