### ISSUE TITLE
Remove Groups module

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#43]
Remove groups module. This will require patching dkan_dataset.info as well as disabling the module.

Please create a PATCHES.txt file in dkan_dataset with a description. Please also create a PATCHES folder in the root directory where you will place the patch.

**Comment by mbrakken** [comment]
I just started on this, and realized I'm not sure if you mean OG, dkan_dataset_groups, or both.

**Comment by acouch** [comment]
Both, thanks. The end goal is to just not have organic groups module installed.

**Comment by mbrakken** [comment]
FYI, if the patch is just to track diffs for record-keeping purposes or intended to be applied against an uninstalled dkan base, there shouldn't be any problems. However, I don't think that the patch will be able to be implemented on a running site since the patch won't be able to run module uninstalls. 

If down the line this is something that should be runnable on an existing site, we'll either need to break it into a cookbook with a series of patches or else create a module which runs the uninstalls. I'm intending for my commits to capture stages. That could go into this.

**Comment by mbrakken** [comment]
Notes to myself:

On branch iss43-remove-og:
1. Disable organic groups access control.
2. Run first commit
3. Disable DKAN Dataset Groups
4. Uninstall Organic Groups Access control and DKAN Dataset Groups
5. Run commits 2 through 4
6. Disable Organic Groups Extras.
7. Disable Organic Groups UI and Organic Groups Context.
8. Disable Organic Groups
9. Uninstall all these.
10. The rest of the commits

But... it didn't work. Group still appears as content type... I'm going to try a much quicker and dirtier approach on a new branch and see what happens.

**Comment by mbrakken** [comment]
I did a version where I just removed all "dependencies[] = og". The Group CT is proving stickier than it ought to be and is not getting removed on uninstall. I'm trying to resolve an OG issue for a different project right now, so I'll see what I can dig up in tandem.
