### ISSUE TITLE
Familiarize yourself with User Roles and Test Adding 'Dataset', 'Blog', 'FAQ', and test adding content as 'contributor'

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#53]

**Comment by acouch** [comment]
Any update on this?

**Comment by mbrakken** [comment]
It's not clear how a "contributor" adds content. Should they be shown a menu at the top of the window or page with sign in/out links, action links, and profile link? They'll need to know paths otherwise, which presents a significant barrier. 

Also, blogger and contributor roles seem redundant right now.

**Comment by mbrakken** [comment]
Tags field on blog is difficult to work with. You can only enter the field by clicking on the far left, not anywhere in the field. Also, placeholder text doesn't clear. The category select list field could also afford some restyling, as the cursor is mostly clipped.
